# Generated by Django 4.2.3 on 2023-08-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslider',
            name='short_description',
            field=models.CharField(max_length=500),
        ),
    ]
