# Generated by Django 4.2.3 on 2023-08-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_alter_bannerslider_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslider',
            name='short_description',
            field=models.CharField(max_length=250),
        ),
    ]
